### ISSUE TITLE
Apply modifications on the class/module level

### ISSUE THREAD

**Issue by Stvad** [robinhilliard/pipes#2]
It'd be great if you could apply the `@pipes` transformation at the level of the class/module instead of having to annotate each function within.

**Comment by robinhilliard** [comment]
Ok, so the unit tests are passing but this will need to get a good try out, particularly of the scopes you'd normally expect to see from your class methods like self, class, module and global. This is because we're recompiling the class but I'm not certain I've preserved the context the original class was in in the recompiled class.

Also look out for problems with step debugging a class because I haven't yet found a way to introspect the line number of the class declaration in the source.

**Comment by robinhilliard** [comment]
Ok 0.3.0 is a big fix and changes some functionality, namely the @pipes(False) argument is no longer supported or required. And step debugging really works now (yay!) for functions and classes because I worked out all the attributes required to get it working properly.  The code is also 15 lines shorter...

**Comment by Stvad** [comment]
cool, I'll give it a try :)

**Comment by robinhilliard** [comment]
Going to close this, please open another ticket if you find any problems related to decorating a class.

**Comment by Stvad** [comment]
Hey, sure! Sorry I didn't have time to experiment with this yet =\
